//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalk.Configuration.Functoids {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalk.Configuration.Functoids.ConfigurationResources", typeof(ConfigurationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDS_BRULESFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_BRULESFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to obtain a definition value from a Vocabulary in the Business Rules Engine.
        ///Input:
        ///- string definitionName (Definition Name e.g. Value1)
        ///- string vocabularyName (Name of Vocabulary i.e. Config).
        /// </summary>
        internal static string IDS_BRULESFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_BRULESFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Engine Config Get.
        /// </summary>
        internal static string IDS_BRULESFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_BRULESFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get definition value from a Vocabulary in the Business Rules Engine.
        /// </summary>
        internal static string IDS_BRULESFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_BRULESFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDS_BTSNTSvcFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_BTSNTSvcFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to get configuration parameters from BTSNTsvc.exe.config. If there is no section specified, the functoid reads from the AppSettings
        ///Input:
        ///- string keyname 
        ///- string section (can be an empty String).
        /// </summary>
        internal static string IDS_BTSNTSvcFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_BTSNTSvcFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTSNTSvc Config Get.
        /// </summary>
        internal static string IDS_BTSNTSvcFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_BTSNTSvcFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Configuration parameters from BTSNTsvc.exe.config.
        /// </summary>
        internal static string IDS_BTSNTSvcFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_BTSNTSvcFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDS_ENVVARCONFFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_ENVVARCONFFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to get configuration parameters from machine System Environment Variable.
        ///Input:
        ///- string key (variable name).
        /// </summary>
        internal static string IDS_ENVVARCONFFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_ENVVARCONFFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns configuration parameters from machine System Environment Variable.
        /// </summary>
        internal static string IDS_ENVVARCONFFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_ENVVARCONFFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Environment Variable Get.
        /// </summary>
        internal static string IDS_ENVVARFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_ENVVARFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDS_FILEFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_FILEFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to get configuration parameters from a custom configuration file.
        ///Input:
        ///- string key (variable name)
        ///- String pathConfigFile (path to the configuration file).
        /// </summary>
        internal static string IDS_FILEFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_FILEFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Config Get.
        /// </summary>
        internal static string IDS_FILEFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_FILEFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns configuration parameters from custom config file.
        /// </summary>
        internal static string IDS_FILEFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_FILEFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDS_REGISTRYFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_REGISTRYFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to get configuration parameters from Windows Registry:
        ///- string subKey (The name or path of the subkey to open)
        ///- String value (The name of the value to retrieve. This string is not case-sensitive).
        /// </summary>
        internal static string IDS_REGISTRYFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_REGISTRYFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Config Get.
        /// </summary>
        internal static string IDS_REGISTRYFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_REGISTRYFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns configuration parameters from Windows Registry.
        /// </summary>
        internal static string IDS_REGISTRYFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_REGISTRYFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDS_SSOFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_SSOFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to get configuration parameters from SSO Database:
        ///- string appName (The name of the affiliate application to represent the configuration container to access)
        ///- String propName (The property name to read).
        /// </summary>
        internal static string IDS_SSOFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_SSOFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO Config Get.
        /// </summary>
        internal static string IDS_SSOFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_SSOFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns configuration parameters from SSO Database.
        /// </summary>
        internal static string IDS_SSOFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_SSOFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap w {
            get {
                object obj = ResourceManager.GetObject("w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
