//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalk.Encoders.Functoids {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EncodersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncodersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalk.Encoders.Functoids.EncodersResources", typeof(EncodersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap IDS_BASE64DECODERFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_BASE64DECODERFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to decode Base64-encoded text strings
        ///Input:
        ///- string data.
        /// </summary>
        internal static string IDS_BASE64DECODERFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_BASE64DECODERFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Decoder Functoid.
        /// </summary>
        internal static string IDS_BASE64DECODERFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_BASE64DECODERFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the result of decoding as string.
        /// </summary>
        internal static string IDS_BASE64DECODERFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_BASE64DECODERFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap IDS_BASE64ENCODERFUNCTOID_BITMAP {
            get {
                object obj = ResourceManager.GetObject("IDS_BASE64ENCODERFUNCTOID_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functoid allows you to convert string object into base64 encoded string
        ///Input:
        ///- string data.
        /// </summary>
        internal static string IDS_BASE64ENCODERFUNCTOID_DESCRIPTION {
            get {
                return ResourceManager.GetString("IDS_BASE64ENCODERFUNCTOID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Encoder Functoid.
        /// </summary>
        internal static string IDS_BASE64ENCODERFUNCTOID_NAME {
            get {
                return ResourceManager.GetString("IDS_BASE64ENCODERFUNCTOID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns base64 encoded string..
        /// </summary>
        internal static string IDS_BASE64ENCODERFUNCTOID_TOOLTIP {
            get {
                return ResourceManager.GetString("IDS_BASE64ENCODERFUNCTOID_TOOLTIP", resourceCulture);
            }
        }
    }
}
