<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalk.MapExtention.LookupFunctoid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsCrmMapHelperResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsCrmMapHelperResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalk.MapExtention.LookupFunctoid.MsCrmMapHelperResource", typeof(MsCrmMapHelperResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_BASETYPE {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_BASETYPE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_GUID {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_GUID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_MONEY {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_MONEY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_OPTVAL {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_OPTVAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_REF {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_REF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field, Target Field Name and Target Field Type (only xsd base type are allowed such as xs:string, xs:int and so on).
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_BASETYPE {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_BASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field and Target Field Name. Use this only for guid type..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_GUID {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field and Target Field Name. Use this only for Money data type..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_MONEY {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field and Target Field Name. Use this only for Option Value data types..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_OPTVAL {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_OPTVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field, Target Field Name and Entity Name. Use this only for reference type..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_REF {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Base Types.
        /// </summary>
        internal static string FUNCTOID_NAME_BASETYPE {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_BASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Guid.
        /// </summary>
        internal static string FUNCTOID_NAME_GUID {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Money.
        /// </summary>
        internal static string FUNCTOID_NAME_MONEY {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Option Value.
        /// </summary>
        internal static string FUNCTOID_NAME_OPTVAL {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_OPTVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper References.
        /// </summary>
        internal static string FUNCTOID_NAME_REF {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Base Types.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_BASETYPE {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_BASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Guid.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_GUID {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Money.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_MONEY {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Option Value.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_OPTVAL {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_OPTVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper References.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_REF {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_REF", resourceCulture);
            }
        }
    }
}
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalk.MapExtention.LookupFunctoid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsCrmMapHelperResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsCrmMapHelperResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalk.MapExtention.LookupFunctoid.MsCrmMapHelperResource", typeof(MsCrmMapHelperResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_BASETYPE {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_BASETYPE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_GUID {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_GUID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_MONEY {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_MONEY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_OPTVAL {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_OPTVAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUNCTOID_BITMAP_REF {
            get {
                object obj = ResourceManager.GetObject("FUNCTOID_BITMAP_REF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field, Target Field Name and Target Field Type (only xsd base type are allowed such as xs:string, xs:int and so on).
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_BASETYPE {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_BASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field and Target Field Name. Use this only for guid type..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_GUID {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field and Target Field Name. Use this only for Money data type..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_MONEY {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field and Target Field Name. Use this only for Option Value data types..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_OPTVAL {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_OPTVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify: Source Field, Target Field Name and Entity Name. Use this only for reference type..
        /// </summary>
        internal static string FUNCTOID_DESCRIPTION_REF {
            get {
                return ResourceManager.GetString("FUNCTOID_DESCRIPTION_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Base Types.
        /// </summary>
        internal static string FUNCTOID_NAME_BASETYPE {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_BASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Guid.
        /// </summary>
        internal static string FUNCTOID_NAME_GUID {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Money.
        /// </summary>
        internal static string FUNCTOID_NAME_MONEY {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Option Value.
        /// </summary>
        internal static string FUNCTOID_NAME_OPTVAL {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_OPTVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper References.
        /// </summary>
        internal static string FUNCTOID_NAME_REF {
            get {
                return ResourceManager.GetString("FUNCTOID_NAME_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Base Types.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_BASETYPE {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_BASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Guid.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_GUID {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Money.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_MONEY {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper Option Value.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_OPTVAL {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_OPTVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCRM Map Helper References.
        /// </summary>
        internal static string FUNCTOID_TOOLTIP_REF {
            get {
                return ResourceManager.GetString("FUNCTOID_TOOLTIP_REF", resourceCulture);
            }
        }
    }
}
>>>>>>> origin/master
